# Generated by Django 5.2.3 on 2025-06-16 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('secteur_activite', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('site_web', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cvs/', verbose_name='CV')),
                ('lettre_motivation', models.FileField(upload_to='lettres/', verbose_name='Lettre de motivation')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_candidature', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='rapports/', verbose_name='Rapport')),
                ('date_soumission', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Note')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='stages.candidature')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du stage')),
                ('type_stage', models.CharField(choices=[('initiation', 'Initiation'), ('perfectionnement', 'Perfectionnement'), ('pfe', "Projet de Fin d'Études")], max_length=20, verbose_name='Type de stage')),
                ('duree', models.CharField(choices=[('1-2', '1-2 mois'), ('3-4', '3-4 mois'), ('5-6', '5-6 mois')], max_length=10, verbose_name='Durée')),
                ('description', models.TextField(verbose_name='Description')),
                ('competences_requises', models.TextField(verbose_name='Compétences requises')),
                ('remuneration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rémunération')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('nombre_places', models.PositiveIntegerField(default=1, verbose_name='Nombre de places')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='stages.entreprise')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.AddField(
            model_name='candidature',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='stages.stage'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('etudiant', 'Étudiant'), ('responsable', 'Responsable'), ('entreprise', 'Entreprise')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='stages.userprofile')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(choices=[('informatique', 'Informatique'), ('gestion', 'Gestion'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('rh', 'Ressources Humaines')], max_length=50)),
                ('niveau_etude', models.CharField(max_length=50)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='stages.userprofile')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
            },
        ),
        migrations.AddField(
            model_name='entreprise',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to='stages.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='candidature',
            unique_together={('stage', 'etudiant')},
        ),
    ]
