# Generated by Django 5.2.3 on 2025-06-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_userprofile_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telephone',
        ),
    ]
