# Generated by Django 5.2.3 on 2025-06-24 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_userprofile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='lettre_motivation',
            field=models.FileField(blank=True, null=True, upload_to='lettres_motivation/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('convention', 'Convention de stage'), ('rapport', 'Rapport de stage'), ('presentation', 'Présentation'), ('attestation', 'Attestation de stage'), ('autre', 'Autre document')], max_length=20, verbose_name='Type de document')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('fichier', models.FileField(upload_to='documents/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='stages.etudiant')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='FicheStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du stage')),
                ('encadrant', models.CharField(max_length=100, verbose_name="Nom de l'encadrant")),
                ('email_encadrant', models.EmailField(max_length=254, verbose_name="Email de l'encadrant")),
                ('telephone_encadrant', models.CharField(max_length=20, verbose_name="Téléphone de l'encadrant")),
                ('mission', models.TextField(verbose_name='Description de la mission')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('date_soutenance', models.DateField(blank=True, null=True, verbose_name='Date de soutenance')),
                ('technologies', models.CharField(max_length=200, verbose_name='Technologies utilisées')),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.entreprise')),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_stage', to='stages.etudiant')),
            ],
            options={
                'verbose_name': 'Fiche de stage',
                'verbose_name_plural': 'Fiches de stage',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=20, verbose_name='Type')),
                ('lien', models.CharField(blank=True, max_length=200, verbose_name='Lien')),
                ('lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
