# Generated by Django 5.2.3 on 2025-06-24 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0005_etudiant_lettre_motivation_userprofile_telephone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='niveau_etude',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='profile',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='niveau',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Niveau d'étude"),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='stages.userprofile'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='lettre_motivation',
            field=models.FileField(blank=True, null=True, upload_to='lettres/', verbose_name='Lettre de motivation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
