# Generated by Django 5.2.3 on 2025-07-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0006_remove_etudiant_niveau_etude_remove_etudiant_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='genre',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], default='M', max_length=1),
        ),
    ]
